version: '3'

services:
  app:
    build: .
    ports:
      - '3001:3001'
    depends_on:
      - 'db'
  db:
    image: 'postgres:17.2-alpine'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
      - ./initdb.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=didomi
      - POSTGRES_PASSWORD=supersafepassword
      - POSTGRES_DB=didomi

volumes:
  postgres_data:
    driver: local
